#!/bin/sh


# git remote add github https://github.com/djmnb/blog.git
# git remote add gitee https://gitee.com/djmnb/hexoblog.git

echo "开始推送"

git push gitee master
if [ $? -eq 0 ]; then
    echo "推送到gitee成功"
else
    echo "推送到gitee失败"
fi

git push github master
if [ $? -eq 0 ]; then
    echo "推送到github成功"
else
    echo "推送到github失败"
fi




