#!/bin/sh


# git remote add github https://github.com/djmnb/blog.git
# git remote add gitee https://gitee.com/djmnb/hexoblog.git

echo "开始推送"
git push -f gitee master
echo "推送到gittee成功"
git push -f github master
echo "推送到github成功"



